### ISSUE TITLE
lesbian not in wordlist.txt but is flagged as a bad word?

### ISSUE THREAD

**Issue by carlinmack** [snguyenthanh/better_profanity#13]
Is there a more complete list or am I missing something

**Comment by shopeonarope** [comment]
It seems to work correctly for me in my repl, that is not censor it.
```
>>> profanity.censor('lesbian')
'lesbian'
```

**Comment by snguyenthanh** [comment]
Hi @carlinmack, sorry for the late reply.

The wordlist in [better_profanity/profanity_wordlist.txt](https://github.com/snguyenthanh/better_profanity/blob/master/better_profanity/profanity_wordlist.txt) is the only wordlist used to generate profanity words.
I'm unable to reproduce the issue on my side. I suggest you may need to upgrade the package on your side to the latest version [better_profanity==0.6.1](https://pypi.org/project/better-profanity).

Although I'm unable to reproduce the issue on my side, I suspect it may be due to it has badly validated the text you gave to it. Are you able to share the text, containing the word `lesbian`, you use ?

**Comment by carlinmack** [comment]
thanks!
