### ISSUE TITLE
Remove some swears

### ISSUE THREAD

**Issue by ThatOneCalculator** [snguyenthanh/better_profanity#9]
I personally don't consider "gay" and "lesbian" profanity. How can I disable them?

**Comment by snguyenthanh** [comment]
Currently, the only way to have your own custom wordlist is to put all words you want in a list, and load them:
```
from better_profanity import profanity

if __name__ == "__main__":
    custom_badwords = ['happy', 'jolly', 'merry']
    profanity.load_censor_words(custom_badwords)
```

Looking back, I think this can be extended to 2 different approaches:
1. To have a keyword argument `whitelist_words` to take a list of words that you don't want to be filtered.
  For example:
  ```
  profanity.load_censor_words(whitelist_words=["gay", "lesbian"])
  ```
2. Instead of manually importing a whole list of words into a list and pass it as an argument to `profanity`, the library should allow users to pass a filename instead. This way, you can just put all the words you want to a `.txt` file and not depend on the library's default wordlist.
  For example:
  ```
  profanity.load_censor_words("/path/to/my/project/my_wordlist.txt")
  ```

I think I will implement both approaches and release them in the next version (which is `0.6.0`). I will keep you updated.

**Comment by snguyenthanh** [comment]
Hi @ThatOneCalculator,
I have released version `0.6.0` with the 2 mentioned features.

For your use case, if `gay` and `lesbian` are the only 2 words that you would like to disable, I would suggest you use the keyword argument `whitelist_words`:

```
profanity.load_censor_words(whitelist_words=['gay', 'lesbian'])
```
More examples can be found at the [README.md](https://github.com/snguyenthanh/better_profanity#6-whitelist).

**Comment by ThatOneCalculator** [comment]
Thank you! This is great. As a member of the LGBTQ community, I personally don't think those words should've made the list in the first place, but thank you so much for this!

**Comment by snguyenthanh** [comment]
> I personally don't think those words should've made the list in the first place

I agree with you. Sorry for any inconvenience caused. I shall remove the words in the next release.

If the issue has been resolved, please feel free to resolve this issue.

**Comment by snguyenthanh** [comment]
Hi @ThatOneCalculator,

The latest version `0.6.1` has been released, and the mentioned words have been removed.
Again, I do apologize for having the words in the wordlist and thank you very much for pointing out.
